---  
- name: change name
  raw: "echo {{hostname|quote}} > /etc/hostname"

- name: "修改主机名" 
  shell: hostname {{hostname|quote}}     

- name: "BASH环境变量修改"
  blockinfile:
    path: /root/.bashrc
    block: |-
        PS1_POOL=$(echo ${HOSTNAME} | tr 'A-Z' 'a-z')
        PS1_DRC=$(ip a | grep -oE "eth0|ens33" | uniq -c | grep -oE "eth0|ens33")
        PS1_IP=$(/sbin/ifconfig eth0 | sed -nr 's/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
        PS1='[${debian_chroot: +($debian_chroot)}\[\033[01;31m\]\u\[\033[00m\]\033[1;33m@\033[0m\033[1;35m$PS1_POOL\033[0m :\033[1;36m $PS1_DRC = $PS1_IP\033[0m \[\033[01;36m\]\w\[\033[00m\]] \t\n\$ '
        export LS_COLORS=$LS_COLORS"*.py=00;35:*.pl=00;32:*.sh=01;32:*.xls=04;36:*.png=04;35;43:*.fa=04;33:*.R=00;32:*.r=00;32:*.vcf=04;35:"
    state: present
    backup: yes

- name: "基础模块安装"
  when: internet == 1
  yum:
    name: "{{ item }}"
    state: present
  loop:
      - gcc
      - gcc-c++
      - lrzsz
      - ntpdate 
      - vim 
      - unzip 
      - sysstat 
      - net-tools
      - epel-release
   
- name: Yum排除kernet
  blockinfile:
    path: /etc/yum.conf
    block: "exclude=kernel*"
      
- name: 时区修改
  shell: rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'ZONE="Asia/Shanghai"' > /etc/sysconfig/clock

- name: 开启系统模块
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - nf_conntrack
    - nf_conntrack_ipv4
    - nf_conntrack_ipv6
    - xt_conntrack
  ignore_errors: yes

- name: 关闭系统服务
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - snmpd
    - postfix
    - firewalld
  ignore_errors: yes

- name: uLimit-90-nproc
  pam_limits:
      dest:  "{{ item.dest }}"
      domain:  '*'
      limit_type:  "{{ item.limit_type }}"
      limit_item:  "{{ item.limit_item }}"
      value:  "{{ item.value }}"
  with_items:
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'soft' ,limit_item:  'nofile' , value:  '655350'  }
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'hard' ,limit_item:  'nofile' , value:  '655350' }
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'soft' ,limit_item:  'nproc' , value:  '102400'  }
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'hard' ,limit_item:  'nproc' , value:  '102400'  }
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'soft' ,limit_item:  'sigpending' , value:  '255377'  }
      - { dest:  '/etc/security/limits.conf' ,limit_type:  'hard' ,limit_item:  'sigpending' , value:  '255377'  }
      - { dest:  '/etc/security/limits.d/90-nproc.conf' , limit_type:  'soft' ,limit_item:  'nproc' , value:  '262144'  }
      - { dest:  '/etc/security/limits.d/90-nproc.conf' , limit_type:  'hard' ,limit_item:  'nproc' , value:  '262144'  }

- name: ulimit参数-systemd
  blockinfile:
    path: /etc/systemd/system.conf
    block: |-
      DefaultLimitNOFILE=102400
      DefaultLimitNPROC=65535
    state: present
    create: yes
    backup: yes

- name: 设置历史记录
  blockinfile:
    path: /etc/profile.d/jiagu.sh
    block: |-
          USER_IP=`who -u am i 2>/dev/null| awk '{print $NF}' |sed -e 's/[()]//g'`
          if [ "\$USER_IP" = "" ];then
          USER_IP=`hostname`
          fi
          HISTSIZE=5000
          TMOUT=36000
          export HISTTIMEFORMAT="%F %T $USER_IP \`whoami\`  "
          shopt -s histappend
          export PROMPT_COMMAND="history -a"
          ######### jiagu history xianshi ##########
          ulimit -S -c unlimited > /dev/null 2>&1
    state: present
    create: yes
    backup: yes

- name: Security安全
  file:
    path: /etc/security
    mode: 600

- name: 账号删除
  user: name="{{item.user}}"  password="{{'123456'|password_hash('sha512')}}" state=absent remove=yes 
  loop:
    - { user: games}
    - { user: adm}
    - { user: shutdown}
    - { user: halt}
    - { user: nacos}
    - { user: operator}
    - { user: zabbix}
    - { user: ftp}
  ignore_errors: yes

- name: 账号组
  shell: groupdel {{ item }}
  loop:
    - games
  ignore_errors: yes

- name: 登录失败处理功能参考配置
  blockinfile:
    path: /etc/default/login
    block: |- 
        RETRIES=5 
        SLEEPTIME=30
    state: present
    create: yes
    backup: yes

- name: 会话超时
  blockinfile:
    path: /etc/profile
    block: |-
        HISTFILESIZE=2000
        HISTSIZE=2000
        HISTTIMEFORMAT='%F_%T' 
        TMOUT=600
    state: present
    create: yes
    backup: yes

- name: 增加 审计员 管理员 操作员用户
  user: 
    name: "{{ item.name }}"  
    group: "{{item.group}}" 
    password: "$6$UJts.K3HfO5/adxe$4u1pVnCs789iahTQYGUPBaJD6qKqPOPriGfTIUvwCbkDdYBAYv8xgNhgfyBGV.G3FhOokRKE5dkjHBMnkTmGx."
  with_items: 
    - {name: "admin", group: "root"}
    - {name: "longshine", group: "root"}
    - {name: "pgname", group: "root"}
